import { useEffect, useRef } from 'react';
import { checkComparisonLabel, downloadFile } from './evidence-brief';
export type DecisionAction = 'sensitivity' | 'drivers' | 'goalSeek' | 'variance' | 'checks';
export const decisionModes: { id: DecisionAction; label: string; description: string }[] = [
  { id: 'sensitivity', label: 'Sensitivity', description: 'Explore two assumptions together. Each case recalculates a disposable workbook copy.' },
  { id: 'drivers', label: 'Drivers', description: 'Rank the effect of changing one input at a time. These local effects do not capture interactions.' },
  { id: 'goalSeek', label: 'Goal seek', description: 'Find an input that reaches a target within your stated bounds and tolerance.' },
  { id: 'variance', label: 'Variance', description: 'Explain the difference between two explicit numeric ranges, matching cells by position.' },
  { id: 'checks', label: 'Check packs', description: 'Test explicit financial rules. Download a reusable pack or import one for review before running.' },
];
export type CheckRule = { label: string; range: string; operator: 'equals' | 'at-least' | 'at-most'; target?: number; compareRange?: string; tolerance?: number };
export const initialRules: CheckRule[] = [{ label: 'Amounts agree', range: 'B11:B13', operator: 'equals', compareRange: 'D11:D13', tolerance: .01 }, { label: 'EBITDA floor', range: 'B8', operator: 'at-least', target: 300000, tolerance: .01 }];
export function DecisionFields({ mode, values, set, rules, setRules, error }: { mode: string; values: Record<string, string>; set: (key: string, value: string) => void; rules: CheckRule[]; setRules: (rules: CheckRule[]) => void; error: (message: string) => void }) {
  const importGeneration = useRef(0);
  useEffect(() => { importGeneration.current++; }, [mode, rules]);
  useEffect(() => () => { importGeneration.current++; }, []);
  const updateRules = (next: CheckRule[]) => { importGeneration.current++; setRules(next); };
  const field = (key: string, label: string, numeric = false) => <label>{label}<input data-testid={`decision-${key}`} type={numeric ? 'number' : 'text'} step={numeric ? 'any' : undefined} required value={values[key]} onChange={e => set(key, e.target.value)} /></label>;
  const edit = (index: number, update: Partial<CheckRule>) => updateRules(rules.map((rule, i) => i === index ? { ...rule, ...update } : rule));
  async function importPack(file?: File) {
    if (!file) return;
    const generation = ++importGeneration.current;
    try {
      if (file.size > 32768) throw new Error('Choose a check pack smaller than 32 KB.');
      const contents = await file.text();
      if (generation !== importGeneration.current) return;
      const parsed = JSON.parse(contents);
      if (parsed.version !== 1 || !Array.isArray(parsed.checks) || parsed.checks.length < 1 || parsed.checks.length > 8) throw new Error('A version 1 check pack must contain 1–8 rules.');
      const clean = parsed.checks.map((r: CheckRule) => {
        if (typeof r.label !== 'string' || r.label.length > 100 || typeof r.range !== 'string' || r.range.length > 64 || !['equals', 'at-least', 'at-most'].includes(r.operator) || (r.compareRange !== undefined ? typeof r.compareRange !== 'string' || r.compareRange.length > 64 || r.target !== undefined : !Number.isFinite(r.target)) || (r.tolerance !== undefined && (!Number.isFinite(r.tolerance) || r.tolerance < 0))) throw new Error('Invalid rule. Check labels, ranges, comparison values and tolerances.');
        return { label: r.label, range: r.range, operator: r.operator, ...(r.compareRange !== undefined ? { compareRange: r.compareRange } : { target: r.target }), tolerance: r.tolerance ?? .01 };
      });
      updateRules(clean); error('');
    } catch (e) { if (generation === importGeneration.current) error((e as Error).message); }
  }
  return <>
    {mode === 'sensitivity' && <>{field('rowInput', 'Row input cell')}{field('rowValues', 'Row assumptions · comma separated')}{field('colInput', 'Column input cell')}{field('colValues', 'Column assumptions · comma separated')}{field('output', 'Output cell')}<p className="field-help">Percentages use decimals: 0.1 = 10%. Colors indicate relative amounts, not whether an outcome is desirable.</p></>}
    {mode === 'drivers' && <>{field('output', 'Output cell')}<div className="rule-card"><span className="eyebrow">FIRST DRIVER</span>{field('driver1', 'Input cell 1')}<div className="form-row">{field('low1', 'Low 1', true)}{field('high1', 'High 1', true)}</div></div><div className="rule-card"><span className="eyebrow">SECOND DRIVER</span>{field('driver2', 'Input cell 2')}<div className="form-row">{field('low2', 'Low 2', true)}{field('high2', 'High 2', true)}</div></div></>}
    {mode === 'goalSeek' && <>{field('goalInput', 'Input to solve')}{field('output', 'Output cell')}{field('target', 'Target output', true)}<div className="form-row">{field('lower', 'Lower input bound', true)}{field('upper', 'Upper input bound', true)}</div>{field('goalTolerance', 'Output tolerance', true)}<p className="field-help">The target must be bracketed by the bounds. A result is not a proof of a unique solution or of behavior outside these bounds.</p></>}
    {mode === 'variance' && <>{field('baseline', 'Baseline amounts')}{field('comparison', 'Comparison amounts')}<p className="field-help">Cells match by position, not account name. Confirm ordering and meaning before interpreting the bridge. The example compares assets with funding, not actual with budget.</p></>}
    {mode === 'checks' && <><div className="pack-toolbar"><button type="button" onClick={() => downloadFile('mog-check-pack.json', JSON.stringify({ version: 1, checks: rules }, null, 2), 'application/json')}>Download pack ↓</button><label className="import-pack">Import pack<input data-testid="import-check-pack" type="file" accept="application/json,.json" onChange={e => { void importPack(e.target.files?.[0]); e.target.value = ''; }} /></label></div><p className="field-help">Imported rules replace this draft only. Review the rules and choose Run to execute them. Packs contain labels and source ranges; share deliberately.</p>{rules.map((rule, index) => <div className="rule-card" key={index}><div className="rule-heading"><strong>Rule {index + 1}</strong><button type="button" aria-label={`Remove rule ${index + 1}`} disabled={rules.length === 1} onClick={() => updateRules(rules.filter((_, i) => i !== index))}>Remove</button></div><label>Rule label<input required maxLength={100} value={rule.label} onChange={e => edit(index, { label: e.target.value })} /></label><label>Source range<input required value={rule.range} onChange={e => edit(index, { range: e.target.value })} /></label><label>Rule<select value={rule.operator} onChange={e => edit(index, { operator: e.target.value as CheckRule['operator'] })}><option value="equals">Equals</option><option value="at-least">At least</option><option value="at-most">At most</option></select></label><label>Compare with<select value={rule.compareRange !== undefined ? 'range' : 'amount'} onChange={e => edit(index, e.target.value === 'range' ? { compareRange: 'D11:D13', target: undefined } : { compareRange: undefined, target: 0 })}><option value="amount">Fixed amount</option><option value="range">Another range total</option></select></label>{rule.compareRange !== undefined ? <label>Comparison range<input required value={rule.compareRange} onChange={e => edit(index, { compareRange: e.target.value })} /></label> : <label>Target amount<input required type="number" step="any" value={rule.target ?? ''} onChange={e => edit(index, { target: e.target.value === '' ? undefined : Number(e.target.value) })} /></label>}<label>Tolerance<input required type="number" min="0" step="any" value={rule.tolerance ?? ''} onChange={e => edit(index, { tolerance: e.target.value === '' ? undefined : Number(e.target.value) })} /></label></div>)}<button type="button" data-testid="add-check" disabled={rules.length >= 8} onClick={() => updateRules([...rules, { label: `Rule ${rules.length + 1}`, range: 'B8', operator: 'equals', target: 0, tolerance: .01 }])}>Add rule · {rules.length}/8</button></>}
  </>;
}
export function decisionPayload(mode: string, v: Record<string, string>, checks: CheckRule[]): Record<string, unknown> | null {
  const n = (key: string) => { if (!v[key]?.trim() || !Number.isFinite(Number(v[key]))) throw new Error('Enter finite numeric assumptions.'); return Number(v[key]); };
  const list = (key: string) => v[key].split(',').map(value => { if (!value.trim() || !Number.isFinite(Number(value))) throw new Error('Enter finite numbers separated by commas.'); return Number(value); });
  if (mode === 'sensitivity') return { rowInput: v.rowInput, colInput: v.colInput, rowValues: list('rowValues'), colValues: list('colValues'), output: v.output };
  if (mode === 'drivers') return { output: v.output, inputs: [1, 2].map(i => ({ cell: v[`driver${i}`], low: n(`low${i}`), high: n(`high${i}`) })) };
  if (mode === 'goalSeek') return { input: v.goalInput, output: v.output, target: n('target'), lower: n('lower'), upper: n('upper'), tolerance: n('goalTolerance') };
  if (mode === 'variance') return { baseline: v.baseline, comparison: v.comparison };
  if (mode === 'checks') return { checks };
  return null;
}
const fmt = (n: number) => new Intl.NumberFormat(undefined, { maximumFractionDigits: 4 }).format(n);
type DecisionResult = { action: string; matrix?: number[][]; rowValues?: number[]; colValues?: number[]; rowInput?: string; colInput?: string; output?: string; baseline?: number; drivers?: { cell: string; lowOutput: number; highOutput: number; lowDelta: number; highDelta: number; span: number }[]; status?: string; solution?: number; value?: number; residual?: number; iterations?: number; baselineTotal?: number; comparisonTotal?: number; difference?: number; rows?: { baselineCell: string; comparisonCell: string; baseline: number; comparison: number; difference: number; percentChange: number | null }[]; passed?: number; failed?: number; checks?: { label: string; range: string; operator?: CheckRule['operator']; tolerance?: number; actual: number; target: number; difference: number; passed: boolean }[] };
export function DecisionResults({ result: raw }: { result: Record<string, unknown> }) {
  const r = raw as DecisionResult;
  if (r.action === 'sensitivity' && r.matrix) {
    const all = r.matrix.flat(); const low = Math.min(...all), high = Math.max(...all);
    return <div data-testid="sensitivity-result"><p className="field-help">Output {r.output} · rows {r.rowInput} / columns {r.colInput}</p><div className="table-scroll"><table aria-label="Sensitivity output values"><thead><tr><th>{r.rowInput} / {r.colInput}</th>{r.colValues?.map((v, i) => <th key={i}>{fmt(v)}</th>)}</tr></thead><tbody>{r.matrix.map((row, i) => <tr key={i}><th scope="row">{fmt(r.rowValues![i])}</th>{row.map((v, j) => <td key={j} style={{ background: `rgba(39,115,87,${.06 + .23 * (high === low ? .5 : (v - low) / (high - low))})` }}>{fmt(v)}</td>)}</tr>)}</tbody></table></div></div>;
  }
  if (r.action === 'drivers' && r.drivers) { const scale = Math.max(1, ...r.drivers.flatMap(d => [Math.abs(d.lowDelta), Math.abs(d.highDelta)])); return <div data-testid="drivers-result"><p className="success">Baseline output {fmt(r.baseline!)}</p><p className="field-help">Each bar is a change from baseline. Low assumption in sage; high assumption in gold. One input changes at a time.</p>{r.drivers.map(d => <div className="driver-result" key={d.cell}><strong>{d.cell}</strong><div className="tornado" aria-hidden="true">{[d.lowDelta, d.highDelta].map((delta, i) => <div key={i} className={`tornado-track tone-${i}`}><i style={{ left: `${delta < 0 ? 50 - Math.abs(delta) / scale * 50 : 50}%`, width: `${Math.abs(delta) / scale * 50}%` }} /></div>)}</div><p>Low: {fmt(d.lowOutput)} ({fmt(d.lowDelta)} change)<br />High: {fmt(d.highOutput)} ({fmt(d.highDelta)} change)</p></div>)}</div>; }
  if (r.action === 'goalSeek') return <div data-testid="goal-seek-result"><div className={r.status === 'converged' ? 'success' : 'warning'}><strong>{r.status === 'converged' ? 'Target reached within tolerance' : 'Target not reached'}</strong><div className="solution-value">Input {String(r.solution)}</div><p>Output {String(r.value)} · residual {String(r.residual)}<br />{r.iterations} iterations</p></div><p className="field-help">Candidate solution only. Review the tested bounds, tolerance and calculation limitations before using it.</p></div>;
  if (r.action === 'variance' && r.rows) return <div data-testid="variance-result"><div className="bridge-summary"><span>Baseline<strong>{fmt(r.baselineTotal!)}</strong></span><span>Change<strong>{fmt(r.difference!)}</strong></span><span>Comparison<strong>{fmt(r.comparisonTotal!)}</strong></span></div><div className="table-scroll"><table><caption>Positional variance bridge</caption><thead><tr><th>Sources</th><th>Baseline</th><th>Comparison</th><th>Change</th><th>%</th></tr></thead><tbody>{r.rows.map((row, i) => <tr key={i}><th scope="row">{row.baselineCell} → {row.comparisonCell}</th><td>{fmt(row.baseline)}</td><td>{fmt(row.comparison)}</td><td>{fmt(row.difference)}</td><td>{row.percentChange === null ? 'N/A' : `${fmt(row.percentChange)}%`}</td></tr>)}</tbody></table></div><p className="field-help">Bridge residual {fmt(r.residual!)}. Percentage change is undefined when baseline is zero. No account or semantic matching is performed.</p></div>;
  if (r.action === 'checks' && r.checks) return <div data-testid="checks-result"><p className={r.failed ? 'warning' : 'success'}>{r.passed} passed · {r.failed} failed</p>{r.checks.map((check, i) => <div className="rule-card" key={i}><strong>{check.passed ? '✓ Passed' : '× Failed'} · {check.label}</strong><p>{check.range}: {fmt(check.actual)}<br />{checkComparisonLabel(check.operator)} {fmt(check.target)} · difference {fmt(check.difference)}<br />Effective tolerance {check.tolerance == null ? '\u2014' : String(check.tolerance)}</p></div>)}<p className="field-help">Passing these explicit rules does not certify the workbook.</p></div>;
  return null;
}
